### ISSUE TITLE
Exception thrown when deleting an appointment after its patient/doctor was deleted first

### ISSUE THREAD

**Issue by MiloTruck** [AY2425S1-CS2103T-T09-3/tp#144]
When entering `delete-appt` after the patient or doctor for that appointment was deleted beforehand, an exception is thrown. Entering the command for the first time will do nothing. Entering the command again (ie. pressing the enter key again for a second time) will display "Invalid Unique ID, appointment does not exist.".

However, if the displayed list is refreshed (eg. entering `list-patient` or `list-doctor`), the appointment will no longer be displayed.

Steps to reproduce:

```
add-doctor n/John Doe p/98765432 e/johndoe@example.com a/123 Clementi Ave 3 s/Orthopedics
add-patient n/Jane Doe p/91234567 e/janedoe@example.com a/456 Clementi Ave 3 d/01-05-1990 g/F t/friend
add-appt pn/Jane Doe dn/John Doe d/23-04-1987 t/1100
delete 2
delete-appt <ID of appointment>
```

Part of the exception thrown:

```
Caused by: seedu.address.model.person.exceptions.PersonNotFoundException
        at seedu.address.model.person.UniquePersonList.setPerson(UniquePersonList.java:61)
        at seedu.address.model.AddressBook.setPerson(AddressBook.java:99)
        at seedu.address.model.ModelManager.setPerson(ModelManager.java:112)
        at seedu.address.logic.commands.DeleteAppointmentCommand.execute(DeleteAppointmentCommand.java:63)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:51)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:177)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:45)
```

**Comment by MiloTruck** [comment]
Potential fix - don't allow deleting of a patient/doctor unless it has no appointments. The user guide has to be updated to specify this behavior.
